version: "3"

volumes:
  rabbitmq:
  postgres:

services:
  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
    ports:
      - "5432:5432"
